title: engineering@squadrun
email: dev@squadrun.co
description: > # this means to ignore newlines until "baseurl:"
  Git ready for some nerd lovin'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://squadrun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  squadrun

# Build settings
markdown: kramdown
permalink: /:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
